REVOKE catalog_manager FROM supervisor;
REVOKE sales_manager FROM supervisor;

ALTER DEFAULT PRIVILEGES FOR ROLE app_user IN SCHEMA catalog
    REVOKE ALL ON TABLES FROM catalog_manager, PUBLIC CASCADE;
ALTER DEFAULT PRIVILEGES FOR ROLE app_user IN SCHEMA catalog
    REVOKE ALL ON SEQUENCES FROM catalog_manager CASCADE;
ALTER DEFAULT PRIVILEGES FOR ROLE app_user IN SCHEMA sales
    REVOKE ALL ON TABLES FROM sales_manager CASCADE;
ALTER DEFAULT PRIVILEGES FOR ROLE app_user IN SCHEMA sales
    REVOKE ALL ON SEQUENCES FROM sales_manager CASCADE;

REVOKE ALL ON ALL TABLES IN SCHEMA catalog FROM catalog_manager, PUBLIC CASCADE;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA catalog FROM catalog_manager CASCADE;
REVOKE ALL ON SCHEMA catalog FROM catalog_manager, PUBLIC CASCADE;

REVOKE ALL ON ALL TABLES IN SCHEMA sales FROM sales_manager CASCADE;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA sales FROM sales_manager CASCADE;
REVOKE ALL ON SCHEMA sales FROM sales_manager CASCADE;